"""job posting table

Revision ID: 3179709ecb92
Revises: 33dd1befa7c8
Create Date: 2018-12-08 23:24:07.429513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3179709ecb92'
down_revision = '33dd1befa7c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_posting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search', sa.String(length=120), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('company', sa.String(length=64), nullable=True),
    sa.Column('age_of_post', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('time_scrapped', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_posting_age_of_post'), 'job_posting', ['age_of_post'], unique=False)
    op.create_index(op.f('ix_job_posting_company'), 'job_posting', ['company'], unique=False)
    op.create_index(op.f('ix_job_posting_search'), 'job_posting', ['search'], unique=False)
    op.create_index(op.f('ix_job_posting_source'), 'job_posting', ['source'], unique=False)
    op.create_index(op.f('ix_job_posting_time_scrapped'), 'job_posting', ['time_scrapped'], unique=False)
    op.create_index(op.f('ix_job_posting_title'), 'job_posting', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_posting_title'), table_name='job_posting')
    op.drop_index(op.f('ix_job_posting_time_scrapped'), table_name='job_posting')
    op.drop_index(op.f('ix_job_posting_source'), table_name='job_posting')
    op.drop_index(op.f('ix_job_posting_search'), table_name='job_posting')
    op.drop_index(op.f('ix_job_posting_company'), table_name='job_posting')
    op.drop_index(op.f('ix_job_posting_age_of_post'), table_name='job_posting')
    op.drop_table('job_posting')
    # ### end Alembic commands ###
